project:
  type: website

website:
  title: "Jan Oledan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



