project:
  type: website
  output-dir: docs

website:
  title: "Jan Oledan"
  navbar: false

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
